title: URL
tagline: "URL manipulation made easy in PHP."
description: "Working with URL can often be much more difficult than you expect. This makes it easy to modify and update any URL."
google_analytics_tracking_id: UA-46050814-6
menu:
    Getting Started:
        Introduction: '/'
        Examples: '/examples/'
        Installation: '/installation/'
    The API:
        Overview: '/overview/'
    The Components:
        Basic: '/components/basic/'
        Complex: '/components/complex/'